<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<EnableDefaultPageItems>true</EnableDefaultPageItems>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Title>TestLibrary2</Title>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Version>1.3.2</Version>
		<Description>Библиотека для Демо Экзамена C#/Wpf/ModernWpfUi/MySql</Description>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="QuickStart\**" />
	  <EmbeddedResource Remove="QuickStart\**" />
	  <None Remove="QuickStart\**" />
	  <Page Remove="QuickStart\**" />
	</ItemGroup>
	<ItemGroup>
		<None Include="readme.txt" Pack="true" PackagePath="." />
		<None Include="DbHelper\readme.txt" Pack="true" PackagePath="DbHelper/" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="ModernWpfUI" Version="0.9.6" />
		<PackageReference Include="MySql.Data" Version="9.2.0" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Dbhelper\" />
	</ItemGroup>
</Project>